// Code generated by "stringer -type CompoundKind"; DO NOT EDIT.

package tnt

import "strconv"

const _CompoundKind_name = "ANDORIF_THEN"

var _CompoundKind_index = [...]uint8{0, 3, 5, 12}

func (i CompoundKind) String() string {
	if i < 0 || i >= CompoundKind(len(_CompoundKind_index)-1) {
		return "CompoundKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompoundKind_name[_CompoundKind_index[i]:_CompoundKind_index[i+1]]
}
