// Code generated by "stringer -type QuantificationKind"; DO NOT EDIT.

package tnt

import "strconv"

const _QuantificationKind_name = "THERE_EXISTSFOR_ALL"

var _QuantificationKind_index = [...]uint8{0, 12, 19}

func (i QuantificationKind) String() string {
	if i < 0 || i >= QuantificationKind(len(_QuantificationKind_index)-1) {
		return "QuantificationKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QuantificationKind_name[_QuantificationKind_index[i]:_QuantificationKind_index[i+1]]
}
