// Code generated by "stringer -type Token"; DO NOT EDIT.

package token

import "strconv"

const _Token_name = "ILLEGALEOFZEROSUCCESSORVARIABLEOPEN_PARENCLOSE_PARENPLUSMULTIPLYEQUALSNEGATIONOPEN_ANGLECLOSE_ANGLETHERE_EXISTSFOR_ALLCOLONANDORIF_THEN"

var _Token_index = [...]uint8{0, 7, 10, 14, 23, 31, 41, 52, 56, 64, 70, 78, 88, 99, 111, 118, 123, 126, 128, 135}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
